---

# Install base roles that are required for all systems
- hosts: deploy_nms
  become: true
  become_method: sudo
  become_user: root
  any_errors_fatal: true
  tasks:
    - name: Create data root
      file:
        state: directory
        path: "{{ nms_data_root }}"
        owner: root
        group: root
        mode: "0755"

    - include_role:
        name: nms
  environment:
    http_proxy: "{{ http_proxy | default('') }}"
    https_proxy: "{{ https_proxy | default('') }}"
    no_proxy: "{{ no_proxy | default('') }}"
