---

# Install base roles that are required for all systems
- hosts: nms
  become: true
  become_method: sudo
  become_user: root
  any_errors_fatal: true
  tasks:
    - when: "apply|default(false)"
      block:
        - include_role:
            name: base
        - include_role:
            name: docker
  environment:
    http_proxy: "{{ http_proxy | default('') }}"
    https_proxy: "{{ https_proxy | default('') }}"
    no_proxy: "{{ no_proxy | default('') }}"

# Install base roles that are required for all systems
- hosts: nms
  become: true
  become_method: sudo
  become_user: root
  any_errors_fatal: true
  tasks:
    - when: "apply|default(false)"
      block:
        - name: Create data root
          file:
            state: directory
            path: "{{ nms_data_root }}"
            owner: root
            group: root
            mode: "0755"

        - include_role:
            name: nms
  environment:
    http_proxy: "{{ http_proxy | default('') }}"
    https_proxy: "{{ https_proxy | default('') }}"
    no_proxy: "{{ no_proxy | default('') }}"
