---

collections:
  - name: community.docker
    version: 3.4.8
  - name: community.general
    version: 6.5.0
  - name: ansible.posix
    version: 1.5.2
  - name: community.crypto
    version: 2.13.1
