---

collections:
  - name: community.docker
    version: 3.4.8
  - name: community.general
    version: 8.6.0
  - name: ansible.posix
    version: 1.5.4
  - name: community.crypto
    version: 2.15.0
